spring.application.name=restaurantBackend
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8

app.security.jwt-secret=Q2hhbmdlVGhpcy1Ub1lvdXJTZWNyZXQtQmFzZTY0LUVuY29kZWQtS2V5
app.security.jwt-expiration-ms=86400000
app.security.admin-prefix=/SUPERSUPERSECRET
app.security.admin-username=admin
app.security.admin-password=change-me
app.security.admin-role=ADMIN
